const queries = {}

queries.all = 'SELECT pelicula.id_pelicula,\n' 
+   'pelicula.titulo_original,\n' 
+   'pelicula.titulo_latino,\n' 
+   'pelicula.foto,\n' 
+   'pelicula.id_tipo,\n' 
+   'pelicula.id_pais,\n' 
+   'pelicula.lanzamiento,\n' 
+   'pelicula.duracion,\n' 
+   'pelicula.resena,\n' 
+   'pelicula.estado,\n' 
+   'estadisticas.cant_vistas,\n' 
+   'estadisticas.cant_likes,\n' 
+   'estadisticas.cant_comentarios\n' 
+ 'FROM\n'
+   'pelicula\n' 
+ 'LEFT JOIN\n' 
+    'estadisticaspelicula\n' 
+       'ON pelicula.id_pelicula = estadisticaspelicula.id_pelicula\n' 
+ 'INNER JOIN\n' 
+    'estadisticas\n' 
  + 'ON estadisticaspelicula.id_estadisticas = estadisticas.id_estadisticas'

queries.one = 'SELECT * FROM pelicula WHERE id_pelicula = ?'

queries.insert = 'INSERT INTO pelicula SET ?'

queries.update = 'UPDATE pelicula SET ? WHERE id_pelicula = ?'

queries.delete = 'UPDATE pelicula SET estado = "F" WHERE id_pelicula = ?'

queries.maxStats = 'SELECT\n'
+   'pelicula.id_pelicula,\n'
+   'pelicula.titulo_original,\n'
+   'pelicula.titulo_latino,\n'
+   'pelicula.foto,\n'
+   'pelicula.id_tipo,\n'
+   'pelicula.id_pais,\n'
+   'pelicula.lanzamiento,\n'
+   'pelicula.duracion,\n'
+   'pelicula.resena,\n'
+   'pelicula.estado,\n'
+   'estadisticas.cant_vistas,\n'
+   'estadisticas.cant_likes,\n'
+   'estadisticas.cant_comentarios\n'
+ 'FROM\n'
+   'pelicula\n'
+ 'LEFT JOIN\n' 
+   'estadisticaspelicula ON\n' 
+       'pelicula.id_pelicula = estadisticaspelicula.id_pelicula\n'
+ 'INNER JOIN\n' 
+   'estadisticas ON\n' 
+       'estadisticaspelicula.id_estadisticas = estadisticas.id_estadisticas\n'
+ 'ORDER BY\n'
+   'estadisticas.cant_vistas DESC,\n'
+   'estadisticas.cant_likes DESC,\n'
+   'estadisticas.cant_comentarios DESC LIMIT 1;'

module.exports = queries